### ISSUE TITLE
New "kawaï" creature for beginners in examples

### ISSUE THREAD

**Issue by CharlotteMaucherat** [jonathanperret/paysage#122]
Hi,

During a lesson with @juliendorra , we had to create something in order to discover Paysage.

Julien asked me to add my creation as a new creature. 

Here is the code :
_You may change some lines to clean it._

```
void draw() {
  background(0);
    noStroke()
    
// EARS
  
fill (0,0,0)
  ellipse (200 , 100 , 100 , 85) ;
  ellipse (400 , 100 , 100 , 85) ;
  
//HEAD

fill (0,0,0)
  ellipse (300, 200, 240, 240) ;
  
//MOUTH

fill (255, 255, 255)
  ellipse (300 , 250 , 110 , 15) ;
  
//CHEEKS

var teinteDeRouge = abs ( sin(millis ()/1000 ) )* 255
var teinteDeVert = abs ( sin(millis ()/500 ) )* 100 + 50
fill(teinteDeRouge, 90, 90, 127)
  ellipse (220 , 240 , 26 , 25) ;
  ellipse (380 , 240 , 26 , 25) ;
  
// WHITE EYES
  
fill (255, 255, 255)
  ellipse (250 , 170 , 50 , 85) ;
  ellipse (350 , 170 , 50 , 85) ;
  
// PUPILS EYES
  
translate (0, abs( sin(millis () / 2000)) *40)
fill (0,0,0)
  ellipse (250 , 170 , 20 , 20) ;
  ellipse (350 , 170 , 20 , 20) ;

}
```

**Comment by juliendorra** [comment]
Thanks @CharlotteMaucherat , I thought it looks cute, simple to hack, and different from what we have. I wanted to have some feedback on whether it would be a good addition to the list of examples

The code might be very accessible from a beginner perspective, as it was wrote by a beginners. 

The only magic part (for persons who forgot math, and they are many) are the `abs ( sin( millis ()/1000 ) )* 255 ` formulas for oscillating variables.
It might be interesting to explain it or to point to an explanation somewhere in the comments. 

![image](https://user-images.githubusercontent.com/109677/46424845-8056c180-c73a-11e8-899d-7d3ceac25e4f.png)

![image](https://user-images.githubusercontent.com/109677/46424858-91073780-c73a-11e8-9de7-6779425ff59a.png)
