### ISSUE TITLE
codecreatureliveparty freezes with an out-of-memory error

### ISSUE THREAD

**Issue by elefevre** [jonathanperret/paysage#128]
The https://www.paysage.xyz/playground/codecreatureliveparty crashes. On opening it, nothing happens. When opening with the Chrome JS console, it stops automatically in Processing.JS, at a place when it detects a potential out-of-memory error.

It is worth noting that at my first opening of the page, I did see a creature, but it frozed after a second or so. At subsequent openings, nothing was displayed.

Browsers tested: Chrome Linux Version 79.0.3945.117, and Firefox Linux 72.0.1.

![image](https://user-images.githubusercontent.com/344414/72594966-10595400-3909-11ea-9a23-d78b87506056.png)

**Comment by jonathanperret** [comment]
That playground contained an absurd number of creatures. I just cleared them all by loading https://www.paysage.xyz/playground/codecreatureliveparty/programmer and turning Preview off as soon as the switch to do so appeared, then clicking to remove all creatures one by one.

Now that playgrounds are persistent, this kind of issue no longer fixes itself with the daily server restart, unfortunately. Added to the fact that the `codecreatureliveparty` playground name is hardcoded in the "kids-friendly" programming interface… 🤷‍♂

**Comment by elefevre** [comment]
Aha! I was still under the impression that creatures were getting deleted every night, so I didn't even think of looking at the programmer page. 
FWIW, I'm considering doing a workshop in pre-school at the end of February. So I'll be keeping this in mind if creatures are already present before the start of the workshop.
Thanks for your help!
