### ISSUE TITLE
Responsive feature for Creatures

### ISSUE THREAD

**Issue by telohtrab** [jonathanperret/paysage#22]
At the moment, the size of a canvas in the creature.pde class is 
    size(document.body.clientWidth, document.body.clientHeight);
but I think when the code is sent, it doesn't "see" the clientWidth and Height so we've got very small creatures on the playground.
Could we get viewers' clientWidth and clientHeight to adjust the size in the class Creature (every other "size" variable depends on global processing native width and height) ?

**Comment by juliendorra** [comment]
try maybe to base your size on:
 size(window.innerWidth, window.innerHeight);
instead?

In any case, the Playground  resize the sketch using this resize function in public/paysagerenderer.js:

var resize = function (sketch) {
  sketch.size(window.innerWidth, window.innerHeight);
};

Each sketch is resized 1. when its received from the server 2.  when the windows is received.

**Comment by telohtrab** [comment]
Seem to work :-) 
Thanks !
