### ISSUE TITLE
Renderer: Code with no background get solid grey background (inc. empty code)

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#24]
Background() are automatically replaced by transparent backgrounds at rendering time, to allow a better cohabitation between the code objects. Basically, we always force a transparent background.

**The replacement is done locally, on the playground Renderer page, because it's for rendering purpose.**
The code is never changed on the server or by the editot before sending, so if they switch and load it again, the users will get their exact same code.

The problem is that if there is no background() command, there is no replacement and the default Background for Processing is a solid (non transparent) grey, that cover everything under it.

That mean that a new empty code send to Paysage will give a solid grey **on top** of all previous code objects :-(

We should detect code without any background and set a background(255, 255, 255, 0).
Either by 
 - adding it in the code text locally in the renderer 
 - or more properly, if it works that way, by setting it locally on the rendering page on the Processing instance via the method

**Comment by jonathanperret** [comment]
Looks like #66 fixes this.
