### ISSUE TITLE
syntax errors in the processing code seems to (sometimes) stop Renderer updates

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#26]
when sending a script with syntax errors, the playground seems to (in some peculiar conditions not yet fully known) stop being updated.

Tested with Creature code, putting for example an é as a parameter instead of a number, or adding some totally garbage code.

The state of the connection (Websocket versus XHR) might have an impact, as it was very easy to get it at Pompidou Center, where Websockets were (apparently) blocked and the renderer had to fall back on XHR.
We tried to reproduce it at home with much less success, with some updating errors (only one object updating on reloading the Playground)

This bug need some more testing:
- send good code to a Playground
- send bad code
- see if blocking Websockets allows the bug to be reproducible

**Comment by jonathanperret** [comment]
Closing as duplicate.
