### ISSUE TITLE
Add better code edition features, integrating a CodeMirror based editor

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#27]
it would nice and easier to work with to have a web editor like CodeMirror in the Programmer,  maybe with Processing syntax highlighting.

It might be heavy and add complexity, some it should start as separate editor forked from the basic one.

**Comment by jonathanperret** [comment]
Being worked on in #42

**Comment by jonathanperret** [comment]
#42 is done and we now have an editor.
