### ISSUE TITLE
Move the example scripts out of programmer.hbs

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#35]
to make the programmer.hbs easier to parse, scroll and update, put the examples in partials.

if possible in .pde files instead of .hbs, giving them a more clear and semantic meaning.

then : 
`<div class="example number-32"> <script type="text/processing">
   {{> number-32}}
</script> </div>`

**Comment by jonathanperret** [comment]
Actually, I was thinking of making the `.pde` files available as static resources and `$.get()`ting them when an example icon is clicked.

**Comment by juliendorra** [comment]
Alas, that would be perceived as slow (click, wait, click again, oh it's here) especially in institutions with sub-effective connections. (We already see that when loading a code object from the list).
Embedding the example scripts give users instantaneous feedback on example click (with the tradeoff of slower first load, of course, but probably invisible to users).
But it make the page hard to modify, so using partials (and preprocessing the page?) seems to strike a balance.

**Comment by jonathanperret** [comment]
Hmm, still not a fan. If the connection really sucks, nothing is going to react with any speed anyway. One could also say that having all the examples in the HTML (and I'd like us to have many more examples!) unnecessarily bloats the initial download.

Note that it wouldn't be hard to preload the examples in the background, getting the best of both: small initial download and fast reaction.

**Comment by juliendorra** [comment]
(I kind of remember that we started with the idea of loading the examples and fell back to embedding)

To summarize:

- putting all the example code in the HTML is unsatisfactory especially for editing and maybe for load time (not sure here, to be tested)
- having the example instantly load is good ux and it would be a shame to loose that
- storing the scripts in real pde files makes sense (but the user probably don't care :-)
- we want to make possible to browse a larger collection of examples. (As a lazy loading carousel?) and that means a way to load the code and it's icon on demand.

Argh…

**Comment by jonathanperret** [comment]
Note that example icons are already loaded separately from the HTML (we're not using `data:` URIs !)
