### ISSUE TITLE
Extend github persistence with GitLab persistence 

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#60]
Following the work in pull request 54 https://github.com/jonathanperret/paysage/pull/54 by @raphaelpierquin
And because GitLab is open source we should extend the persistence efforts using GitLab API 
https://docs.gitlab.com/ee/api/README.html

**Comment by jonathanperret** [comment]
Well #54 still has a way to go before merging, who knows what may happen 😄

**Comment by jonathanperret** [comment]
Feels weird to have this open when the GitHub persistence option is still on the back-burner.
