### ISSUE TITLE
Focus back in editor after clicking Go Live ! button

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#71]
On the programmer, when we click [Go Live !], the interface focus is not in the code editor anymore.

Thus, when we try and resume our typing to change our code, nothing happen. We have to manually click on the editor space to make it the focus again. In a programming session we might send our code many times, clicking back on the editor each time.

It would be preferable to be able to resume our programming without effort, event letting our cursor hovering the [Go Live!] button.

We have a couple of possible solution in term of UX:

- like in LiveCodeLab, all typing always go to the editor. (we hijack the typing). See livecodelab.net/play/index.html for the behavior. It has the advantage of flow, but might lead to some unexpected behaviors, as no other elements would react to typing. What about the Code Object name for example?

- we specifically handle the "press Go Live!" case, and on clicking the button we take care of returning the focus to the code editor

**Comment by jonathanperret** [comment]
Agreed that "Go live" should put the focus back in the editor. I'd also like a keyboard shortcut to go live without having to reach for the mouse!
