### ISSUE TITLE
Grey background is back when error code in setup

### ISSUE THREAD

**Issue by etienneCharignon** [jonathanperret/paysage#76]
In cas you make a syntax error in the setup function, you get no creature but a grey background covering the full playground and all code objects in layers below.

For example, add a correct code object to the playground and then create an object with the following code.

```
void setup() {
    noStroke()
    syntaxError
}

void draw() {
    background (0)
   
    var deplacement = sin (millis()/50) * 20
    translate (deplacement, 30)
    
    fill (10, 50, 10, 10)
    rect (10, 10, 100, 100)
}
```

**Comment by juliendorra** [comment]
to narrow it down:
if you have a background set up before the syntax error in `setup()`, the background is correctly set. (but not after, as obviously it's never ran)

Exemple, this lead a transparent background

```
void setup() {
    background (0, 0)
    noStroke()
    syntaxError
}

void draw() {
    background (0)
   
    var deplacement = sin (millis()/50) * 20
    translate (deplacement, 30)
    
    fill (10, 50, 10, 10)
    rect (10, 10, 100, 100)
}
```
