### ISSUE TITLE
Undefined errors in draw() are not caught, no helpful log message

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#81]
This is a list of 3 different errors, 
The first 2, a syntax error and a undefined in setup()  are caught and lead to a helpful message log in the console.
The last one shows that undefined errors in draw() are not caught and don't lead to a helpful message.

All code objects errors should as much as possible lead to a unified behavior and alert. There might be other cases that I didn't think of and didn't  test.

## 1. Omit the last } 

This case happened in class with some of my students and could be a frequent error made by beginners.

```
void setup() {
    background (0, 0)
    noStroke()
}

void draw() {
    background (0)
    var deplacement = abs(sin (millis()/50)) * 50
    translate (deplacement, 30)
    fill (10, 50, 10, 10)
    rect (10, 10, 100, 100)

// syntax error, no closing }
```

### Present Behavior
The error is caught and a helpful message is printed on the console 
> Error in code object jietno. Code not rendered. SyntaxError: Unexpected token var

## Undefined function or variable in setup()

```
void setup() {
    background (0, 0)
    noStroke()
    notDefined // this is undefined
}

void draw() {
    background (255)
    var deplacement = abs(sin (millis()/50)) * 50
    translate (deplacement, 30)
    fill (10, 50, 10, 10)
    rect (10, 10, 100, 100)
    
}
```
### Present behavior
The error is caught and a helpful message is printed on the console 
> Error in code object jietno. Code not rendered. SyntaxError: Unexpected identifier

## Undefined function or variable in draw()

```
void setup() {
    background (0, 0)
    noStroke()
}

void draw() {
    background (255)
    var deplacement = abs(sin (millis()/50)) * 50
    translate (deplacement, 30)
    fill (10, 50, 10, 10)
    rect (10, 10, 100, 100)
    notDefined // this is undefined
}
```
### Present behavior
The error is **not** caught. A javascript error is printed, but without an helpful hint of where it comes from
> Uncaught ReferenceError: notDefined is not defined

**Comment by jonathanperret** [comment]
Yeah, compilation errors are caught when setting up the sketch, as are runtime errors in `setup()` since it is run synchronously. But runtime errors in `draw()` only happen later once it's a Processing instance running the show in a timer, so it's a bit more difficult to catch those errors. But there are probably some things we could try…
