### ISSUE TITLE
Sending objects list as JS object makes order unreliable

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#85]
Order of objects in the list in the programmer is not guaranteed, as the list is send as a Javascript object, not an Array or a (newer) Map object.
An example is integers in Chrome: they are considered index, and treated before non-index

Example, try that on Chrome:

- send objects called "one", "two", "three", "four". They appear in a coherent order, being added one after another in a regular manner.
- now send an object named "1". It will not be added after "four", but before "one"
- now send an object called  "34", it will appear in between "1" and "one"

The behavior should be different on Firefox. 

Some context: https://stackoverflow.com/a/23202095

We should send or transform the objects list as an array or map object to get a reliable order.

**Comment by jonathanperret** [comment]
Thanks, I can’t believe I missed this. Since order is important to us, arrays seem the right solution here (apart from partial browser support and having to insert entries in the order you want them, you can’t “send” a `Map` unless you define an unequivocal serialization format for them).
