### ISSUE TITLE
Programmer: a keyboard shortcut for user to send Code Object

### ISSUE THREAD

**Issue by juliendorra** [jonathanperret/paysage#91]
It could be useful for users to send their code without using the mouse, trackpad or touchscreen to click the [Go Live!] button– keeping their hands on the keyboard.

Meta + Return (as in Command+return on Mac, Windows Key+Return on Windows…)

seems a good choice.

We track keyboard keydown events, and initiate a send if the right keys are combined, with a debounce until keyup.

**Comment by jonathanperret** [comment]
Yes, I’ve been wishing for this shortcut. Let’s look at how other online code editors do it – I’m pretty sure WindowsKey+Return is not right for Windows, for example.
